# This is the docker-compose script for local development.
# For the latest version of the docker images see:
# https://github.com/Azure/pcs-cli/blob/master/remotemonitoring/single-vm/docker-compose.dotnet.yml
#
# Usage:
# - install Docker Compose, see https://docs.docker.com/compose/install
# - open a console and `cd` into the folder that contains this file
# - note how this file references many environment variables, either set
#   them in the .env file or edit this file adding the values here
# - run `docker-compose up`
# - open the browser at http://127.0.0.1:10443
#
# For more information see
# https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet

version: "3"

services:
  reverseproxy:
    image: vschinaiot/remote-monitoring-nginx:testing
    ports:
      - "8080:80"
    depends_on:
      - webui
      - auth
      - iothubmanager
      - devicesimulation
      - telemetry
    volumes:
      - ./config/nginx.conf:/app/config/nginx.conf:ro

  webui:
    image: vschinaiot/pcs-webui:testing
    depends_on:
      - auth
      - iothubmanager
      - devicesimulation
      - telemetry
  # NOTE: Volumes disabled for local development, uncomment if enabling auth
  # volumes:
  #   - ./webui-config.js:/app/build/webui-config.js:ro

  auth:
    image: vschinaiot/pcs-auth:testing
    environment:
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_APPLICATION_SECRET

  iothubmanager:
    image: vschinaiot/pcs-iothub-manager:testing
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_CONFIG_WEBSERVICE_URL=http://config:9005/v1
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_APPLICATION_SECRET

  devicesimulation:
    image: vschinaiot/pcs-device-simulation:testing
    depends_on:
      - storageadapter
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022/v1
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_APPLICATION_SECRET
  # How one could mount custom device models
  # NOTE: Volumes disabled for local development
  # volumes:
  #   - ./my-device-models:/app/data:ro

  telemetry:
    image: vschinaiot/pcs-telemetry:testing
    depends_on:
      - storageadapter
    environment:
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022/v1
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_APPLICATION_SECRET

  storageadapter:
    image: vschinaiot/pcs-storage-adapter:testing
    environment:
      - PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_APPLICATION_SECRET

  telemetryagent:
    image: vschinaiot/pcs-telemetry-agent:testing
    depends_on:
      - telemetry
      - iothubmanager
    environment:
      - PCS_TELEMETRYAGENT_DOCUMENTDB_CONNSTRING
      - PCS_TELEMETRY_WEBSERVICE_URL=http://telemetry:9004/v1
      - PCS_CONFIG_WEBSERVICE_URL=http://config:9005/v1
      - PCS_IOTHUBMANAGER_WEBSERVICE_URL=http://iothubmanager:9002/v1
      - PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT
      - PCS_IOTHUBREACT_AZUREBLOB_KEY
      - PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX
      - PCS_IOTHUBREACT_HUB_NAME
      - PCS_IOTHUBREACT_HUB_ENDPOINT
      - PCS_IOTHUBREACT_HUB_PARTITIONS
      - PCS_IOTHUBREACT_ACCESS_CONNSTRING
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_APPLICATION_SECRET